wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("edit/<str:name>/", views.edit, name="edit"),
    path("random", views.random, name="random"),
    path("search", views.search, name="search"),
    path("<str:entry>", views.entry, name="entry"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("wiki/", include("encyclopedia.urls")),
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import re
from random import randrange

from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from markdown2 import Markdown

from . import util

markdown = Markdown()

"""
list_entries():
Returns a list of all names of encyclopedia entries.

save_entry(title, content):
Saves an encyclopedia entry, given its title and Markdown
content. If an existing entry with the same title already exists,
it is replaced.

get_entry(title):
Retrieves an encyclopedia entry by its title. If no such
entry exists, the function returns None.
"""


class NewEntryForm(forms.Form):
    title = forms.CharField(label="New Entry")
    content = forms.CharField(widget=forms.Textarea)


class EditEntryForm(forms.Form):
    title = forms.CharField(label="Edit Entry")
    content = forms.CharField(widget=forms.Textarea)


def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


def entry(request, entry):
    fetched_entry = util.get_entry(entry)
    if fetched_entry is None:
        return render(
            request, "encyclopedia/error.html", {"error": f"{entry} not found"}
        )

    return render(
        request,
        "encyclopedia/entry.html",
        {"entry": markdown.convert(fetched_entry), "name": entry},
    )


def new(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            e = util.get_entry(title)
            if e is None:
                util.save_entry(title, content)
            else:
                return render(
                    request,
                    "encyclopedia/error.html",
                    {"error": f"Encyclopedia entry {title} already exists"},
                )

            # validate validate validate
            return HttpResponseRedirect(title)

    return render(request, "encyclopedia/new.html", {"form": NewEntryForm()})


def edit(request, name):
    e = util.get_entry(name)

    if request.method == "POST":
        form = EditEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            if e is not None:
                util.save_entry(title, content)

                # validate validate validate title
                return HttpResponseRedirect(
                    reverse("encyclopedia:entry", kwargs={"entry": title})
                )

    form = EditEntryForm({"title": name, "content": e})
    return render(request, "encyclopedia/edit.html", {"form": form})


def random(request):
    max = len(util.list_entries())
    e = util.list_entries()[randrange(max)]
    return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"entry": e}))


def search(request):
    found_entries = []
    entry_list = util.list_entries()

    query = request.GET.get("q", "")
    fetched_entry = util.get_entry(query)

    if fetched_entry is None:
        for entry in entry_list:
            # test (partial) match against regex
            regex = re.search(query, entry)

            if regex is None:
                # display error when no entries (partially) matching were found
                pass
            else:
                # append result to list
                index = entry_list.index(entry)
                found_entry = entry_list[index]
                found_entries.append(found_entry)

        if len(found_entries) == 0:
            return render(
                request, "encyclopedia/error.html", {"error": f"{query} not found"}
            )

        # when for loop is done send list to template
        return render(request, "encyclopedia/index.html", {"entries": found_entries})

    return render(
        request,
        "encyclopedia/entry.html",
        {"entry": markdown.convert(fetched_entry), "name": query},
    )

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit Entry
{% endblock %}

{% block body %}
<h1>Edit Entry</h1>
<form action="{% url 'encyclopedia:edit' name=form.data.title %}"
      method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit">
</form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ name }}
{% endblock %}

{% block body %}
{{ entry|safe }}
<a href="{% url 'encyclopedia:edit' name %}">Edit Entry</a>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Error
{% endblock %}

{% block body %}
<h1>Error</h1>
<p>{{ error }}</p>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li><a href="{% url 'encyclopedia:entry' entry %}">{{entry}}</a></li>
    {% endfor %}
</ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}"
          rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'encyclopedia:search' %}"
                  method="get">
                <input class="search"
                       type="text"
                       name="q"
                       placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:random' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create New Page
{% endblock %}

{% block body %}
<h1>Create New Page</h1>
<form action="{% url 'encyclopedia:new' %}"
      method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit">
</form>
{% endblock %}